Create ,ultiple files in modules and add import and exports to differ…
richardoppiyo/Awesome-books-beta pull request #1
Opened 2022-02-14 20:44 UTC by richardoppiyo

In this milestone:
- Initialized the project with npm
- I created modules folder, added multiple js files and used import and exports to link the files.
- implemented  date time using luxon dependency.

2022-02-14 22:37 UTC, richardoppiyo commented
The Linter error is connected to node_modules. I have tried to find a way to disable that but I can't find it. I am not  sure if its an issue with the version of npm or what? Kindly advice.

2022-02-14 22:53 UTC, brytebee commented
Hi, @richardoppiyo 
Have you tried removing and re-installing the linter files?

2022-02-14 22:57 UTC, richardoppiyo commented
> Hi, @richardoppiyo Have you tried removing and re-installing the linter files?

Yes, I have tried that but it didn't solve that. I have also re- installed node_modules but it didn't fix the issue

2022-02-14 22:59 UTC, brytebee requested changes
Hi, @richardoppiyo 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

You have submitted a project with linter errors. Kindly fix the linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-15 09:59 UTC, Meltrust reviewed
Hi @richardoppiyo,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a readme.  Please, remember that for all projects it is mandatory to use the complete [Microverse template](https://github.com/microverseinc/readme-template).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-15 13:16 UTC, FrederickMih requested changes
### Hi @richardoppiyo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 13:16 UTC, FrederickMih commented on modules/Book.js
> +export class Book {
- [ ] Please let's refactor our classes to ES6 functions, this way, we meet the project requirements and get closer to approval.

2022-02-15 13:16 UTC, FrederickMih commented on modules/BookList.js
> +export default class BookList {
- [ ] Please let's refactor our classes to ES6 functions, this way, we meet the project requirements and get closer to approval. 
You may consider doing something like `export const bookList = () => {
  code
}`;

2022-02-15 13:16 UTC, FrederickMih commented on modules/navigation.js
> +export default class Navigator {
- [ ] As mentioned above, please let's refactor our class to ES6 function.

2022-02-15 17:57 UTC, richardoppiyo commented
Re-submitting as advised by CR

2022-02-15 19:11 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @richardoppiyo 👋🏻, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 19:25 UTC, merged